server:
  port: 8080

spring:
  application:
    name: hospital-registration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital_registration?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: baixiaochun2004

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hospital.registration.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.hospital.registration: debug
  file:
    name: logs/hospital-registration.log
